### PR TITLE
Enhancements to the tutorial template

### PR DESCRIPTION
**Pull request by jonathanbossenger**
Suggested improvements to the tutorial GitHub issue template.

More closely follows the tutorial creation process, with updated links to the relevant documentation in the handbook.

### CODE REVIEW

**Comment by kaitohm** [comment]
I have reviewed the suggested changes. These make sense to me and looks good to go 👍

**Comment by vagelisp** [comment]
I agree with Ben. Looking good. Well done.

**Comment by wparasae** [comment]
Agreed. Looks great!

**Comment by westnz** [comment]
Looks great!  Thank you so much @jonathanbossenger 

Three considerations I was thinking about:

1. Could 29 and 30 be combined?
2. Could 31 and 32 be combined?
3. Could we remove 37 and 38? When a tutorial is published, it is automatically shared in the Training Team channel. I also thought the creator would already know when the Tutorial will go live.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback, everyone. 

@westnz to your specific questions:

1. Could 29 and 30 be combined? _I don't see why not, PR updated_
2. Could 31 and 32 be combined? _I think there is a situation where folks can submit videos to WPTV, but need a WPTV mod to publish it, so this might not be possible._
3. Could we remove 37 and 38? _Yeah I think this also makes sense, PR updated_

**Comment by jonathanbossenger** [comment]
Thanks, everyone, I have merged the changes. Next, I will review our lesson plan checklist for similar possible improvements/updates.

**Pull request merged**
