### PR TITLE
Improve Learning Pathway section no results message

### LINKED ISSUE #2633: Improve "no pathways found" message
We could use a better message or design treatment for “No [pathways] found.”:

Image

Maybe just a border:

Image

### PR DESCRIPTION
**Pull request by adamwoodnz**
Closes #2633 

| Before | After |
|--------|--------|
| learn wordpress org_learning-pathway_user__new-theme=1(Desktop) (1) | learn wordpress org_learning-pathway_user__new-theme=1(Desktop) |

### CODE REVIEW

**Comment by adamwoodnz** [comment]
@WordPress/meta-design should we use this bordered block style consistently across the site? eg. cases like this:

Image

**Comment by jasmussen** [comment]
Looks good! Yes, can use the same style for anything that returns empty.

**Review by outdoor2kode — APPROVED** [review]
LGTM 👍

**Comment by adamwoodnz** [comment]
> Looks good! Yes, can use the same style for anything that returns empty.

Nice, here are some sample screenshots

| Home | LPs | Courses | Lessons |
|--------|--------|--------|--------|
| localhost_8888_(2 1366x768) | localhost_8888_learning-pathways_(2 1366x768) | localhost_8888__s=fhdt post_type=course(2 1366x768) | localhost_8888__s=blah post_type=lesson(2 1366x768) |

**Pull request merged**
