### PR TITLE
Add script to count unique learners

### PR DESCRIPTION
**Pull request by kaitohm**
Adds the script provided by @m1r0 in #2111 to wporg-learn plugin

### CODE REVIEW

**Comment by kaitohm** [comment]
I'll come back to clean up those errors tomorrow.

**Comment by kaitohm** [comment]
I've given it my best shot, but I'm unsure how to fix the remaining three errors.
@jonathanbossenger Could you have a look at this for me, please? Thanks 🙇

**Comment by jonathanbossenger** [comment]
@bsanevans sure thing. Would you prefer to see the fixes and explanations during a call, or would you prefer me to push the fixes to this PR, with a summary of the changes and why the PHP static analysis tool requires them?

**Comment by kaitohm** [comment]
Closing in favor of #2172 .

**Pull request closed without merging**
