### PR TITLE
Fixed Firefox Lesson Plan Overlap issue for all languages

### PR DESCRIPTION
**Pull request by shail-mehta**
Fixed Lesson Plan Overlap Issue with Sidebar for All Languages in Firefox.

### CODE REVIEW

**Comment by shail-mehta** [comment]
Fixes https://github.com/WordPress/Learn/issues/1888

**Review by speedyprem — APPROVED** [review]

**Comment by jonathanbossenger** [comment]
Hi @shail-mehta thank you for your PR.

There seem to be some conflicts on this PR. Would you be able to refresh it, so that we can get it merged?

Thanks

**Comment by shail-mehta** [comment]
@jonathanbossenger Thanks for the feedback.

I have Resolved Conflicts issue & also refresh the PR With current trunk. 

Can you please review it?

**Comment by ironnysh** [comment]
The redesign resolved #1888. This PR can be closed.

CC @jonathanbossenger

**Pull request closed without merging**
