### PR TITLE
Enforce login when accessing My Courses page

### LINKED ISSUE #2538: My Courses logged out state
When attempting to log in after taking a course, the default Sensei login form is broken on mobile.

1. Make sure you’re logged out
1. Go to https://learn.wordpress.org/course/beginner-wordpress-user/
1. Click on Take Course

You are redirected to the My Courses page at this URL: https://learn.wordpress.org/my-courses/ which renders the Sensei login form.

However, the form is broken on mobile:

learn wordpress org_my-courses__redirect_to=https___learn wordpress org_lesson_planning-content-for-success_

It's possible this used to take you to a [WordPress.org](https://login.wordpress.org/) login page, but I can't verify this. 

It appears that the reason this is currently happening is that the Sensei [/includes/class-sensei-frontend.php](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/class-sensei-frontend.php#L1088) file wraps the login form inside a div with the class attribute of col-1, which we define in our stylesheet as having a width of 8.3333333333%.

I'm unaware of any recent changes to Learn that might have caused this, so it might be a .org-related or Sensei-related issue.

### PR DESCRIPTION
**Pull request by adamwoodnz**
Fixes #2538 

Redirects requests for the My Courses page to the login page, and back to My Courses.

**NOTE: Should not be merged until we have custom copy on the login page, similar to what we have for [wordcamp.org logins](https://login.wordpress.org/?from=wordcamp.org).**

### Testing
1. Ensure you are logged out
2. Click the 'My Courses' link in the local nav
3. You should be taken to the login page, with a `redirect_to` parameter for the My Courses page. In prod that is https://login.wordpress.org/?redirect_to=https%3A%2F%2Flearn.wordpress.org%2Fmy-courses
4. Log in and you should arrive on the My Courses page.
5. Log out again
6. Go to a Course or Lesson and click the 'Take this Course' button
7. You should be taken to the login page, with a `redirect_to` parameter for taking the current course, eg. https://login.wordpress.org/?redirect_to=https%3A%2F%2Flearn.wordpress.org%2Fcourse%2Fbeginner-wordpress-user%2F%3Ftake_course_sign_in%3D1
8. Log in and you should be redirected back to the course and be enrolled.

### CODE REVIEW

**Review by outdoor2kode — APPROVED** [review]
LGTM 👍 Except:

> Log in and you should be redirected back to the course and be enrolled.

When I am redirected back, I am not automatically enrolled, either locally or on the sandbox. This does not appear to be the behavior in production either.

**Comment by dd32** [comment]
I don't think this removes the need for any of the custom additions I added to the Sensei login/registration.

But I think we can open-source the changes now (I've pushed it to this PR) and deploy it.

**Comment by dd32** [comment]
Ah, of course my code doesn't match the linting requirements :) Other than the whitespace, those can be disregarded IMHO...

**Review by dd32 — APPROVED** [review]

**Comment by adamwoodnz** [comment]
> LGTM 👍 Except:
> 
> > Log in and you should be redirected back to the course and be enrolled.
> 
> When I am redirected back, I am not automatically enrolled, either locally or on the sandbox. This does not appear to be the behavior in production either.

Yeah you're right, the user isn't enrolled. Just redirected back to start the course.

**Pull request merged**
