### PR TITLE
Build Tools: Add php, js, and sass linters

### PR DESCRIPTION
**Pull request by ryelle**
This PR is absurd, but adds eslint & stylelint by way of wp-scripts, and phpcs using the WordCamp customized ruleset.

PHPCS can be installed and run with composer.

```
composer update # (or install if you haven't installed yet)
composer run lint
composer run format # to fix any fixable issues
```

This will flag `plugins/wporg-learn/inc/class-lesson-plan.php`, those fixes need a bit more background than I have. Also, `themes/pub/wporg-learn-2020/page-lesson-plans.php` isn't using the translation functions at all.

eslint & stylelint are run using yarn:

```
yarn workspaces run lint:js # This will fail on the theme since there's no JS, but I left it since #59 might happen
yarn workspaces run lint:css
```

I also updated the workspace names to be more clear, so you can run in individual workspaces like so:

```
yarn workspace wporg-learn-plugin lint:js
yarn workspace wporg-learn-theme lint:css
```

Eventually we should add github actions to run these on each PR, until then each dev should run it before making a PR.

### CODE REVIEW

**Comment by CdrMarks** [comment]
@ryelle, are any of the commands you mentioned necessary to setup a local development environment?  If so, should these be added to the **readme.md** file?

**Comment by StevenDufresne** [comment]
Great! Are we trying to get this in pre-launch? I'm thinking maybe we can wait.

**Comment by ryelle** [comment]
Definitely post-launch 👍  My thought was to get the PR up early to avoid merge conflicts, but we're already there— so I'll switch this back to draft and get better docs written.

**Comment by ryelle** [comment]
Updated everything here, added docs briefly mentioning each command [to the readme,](https://github.com/WordPress/learn/tree/update/devex#development) and added a workflow to run all the linters on PRs using github actions (🤞 , if I set it up correctly).

**Comment by ryelle** [comment]
Okay, fixed all the conflicts, and fixed the github action. It's [still failing on the one PHP file,](https://github.com/WordPress/learn/pull/71/checks?check_run_id=982133715) `plugins/wporg-learn/inc/class-lesson-plan.php`, but these functions seem to be duplicated from the markdown plugin.

**Comment by coreymckrill** [comment]
Hoping to remove those functions anyway: #85

**Review by coreymckrill — APPROVED** [review]
This looks great!

**Pull request merged**
