### PR TITLE
Adding //lesson automation

### PR DESCRIPTION
**Pull request by jonathanbossenger**
Add the //lesson automation, which allows contributors and faculty to automate the process of adding the Lesson Creation checklist to new Lesson issues

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
Note that we can only merge this once the new [Lesson Creation guidelines](https://docs.google.com/document/d/1twvDGmVZsyjBZbi9abiqoA_a2G7O_WNis_iGL2Sccg0/edit?usp=sharing) have been published, as we will have to add links to the relevant new handbook pages.

**Comment by kaitohm** [comment]
Actually, in its current state, the `//lesson` command is going to trigger both the Lesson check list and the Lesson Plan check list... The last English (non-translated) Lesson Plan published on Learn seems to be in July 2022. As Faculty haven't created a new lesson plan in 18 months, and as that check list is most likely not going to be used, what do you think about removing the lesson plan trigger and check list all together?

Also noting https://github.com/WordPress/Learn/blob/trunk/.github/ISSUE_TEMPLATE/02-content-development-faculty.md will need to be updated as part of these changes.

**Comment by jonathanbossenger** [comment]
Out of interest, when you set up the automations, did you try using [Operators](https://docs.github.com/en/actions/learn-github-actions/expressions#operators) instead of [functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions) to test the `if` condition?

Looking at the documentation

```
if: ${{ inputs.content-type == 'lesson' }}
```

and 

```
if: ${{ inputs.content-type == 'lesson-plan' }}
```

Should perform an "is equal to" check, and therefore only return true if it's an exact match.

**Comment by jonathanbossenger** [comment]
> Also noting https://github.com/WordPress/Learn/blob/trunk/.github/ISSUE_TEMPLATE/02-content-development-faculty.md will need to be updated as part of these changes.

Good point, I will create a PR for those in the new year, and then we can review and merge all three together.

**Review by kaitohm — APPROVED** [review]
I've modified the lesson plan command so that it doesn't conflict with the new lesson command.

**Comment by kaitohm** [comment]
> Out of interest, when you set up the automations, did you try using [Operators](https://docs.github.com/en/actions/learn-github-actions/expressions#operators) instead of [functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions) to test the if condition?

Nope, no particular reason. I'm brand new at this and mostly copying things I'm seeing other folks do 😅 

On that note, the `==` operator looks like it would work for `comment-with-checklist.yml` where we're comparing an input against the keywords.

However, for `content-checklist-from-issue.yml`, the function `contains(github.event.issue.body, '//lesson')` would still pickup `//lesson-plan` if it existed, so I feel like the two keywords should still be different.

**Comment by jonathanbossenger** [comment]
@bsanevans checking in here, is this ready to be merged?

**Pull request merged**
