### PR TITLE
Upgrade Sensei Pro to v 1.15.0

### LINKED ISSUE #1606: Upgrade Sensei Pro to v 1.15.0
The last time Sensei Pro was updated was [November 2022](https://github.com/WordPress/Learn/pull/1075).

I'm opening this ticket in order to create a PR to get this updated

### PR DESCRIPTION
**Pull request by jonathanbossenger**
Closes #1606 

The last manual Sensei Pro update was in November 2022.

### CODE REVIEW

**Comment by alexstine** [comment]
@jonathanbossenger I want to test this but do not have a Sensei Pro license key. Can you reach out via Slack and provide one? Not sure how to test without.

**Comment by jonathanbossenger** [comment]
@alexstine, my apologies, I wasn't aware it needed the key to test. I'll DM you in Slack on Monday.

**Review by alexstine — APPROVED** [review]
@jonathanbossenger From what I can tell, this seems to be working well. Local environment is not working all that great though so I am not super confident in my testing. I need to take some time at some point and figure out why some of these fatal errors are happening. Seems like some type of Composer problem on my system.

I think we just need to work with Meta and make sure this deploy goes well. Probably need to update the base/free plugin in SVN I guess, looks like its all Composer for our repo.

**Review by adamwoodnz — APPROVED** [review]
I've run this locally and on my sandbox and executed the tests listed [here](https://github.com/WordPress/Learn/pull/1075#issuecomment-1301661033) by Hugh. I also tried using the new [AI quiz generation feature](https://senseilms.com/introducing-ai-powered-quiz-generation/) mentioned in the changelog, but it appears we'll need a license key, which I'm surprised we don't have in prod.

Screen Shot 2023-06-21 at 2 18 15 PM

Otherwise I can't see any regressions, LGTM

**Comment by jonathanbossenger** [comment]
Thanks for testing @alexstine and @adamwoodnz 

> but it appears we'll need a license key, which I'm surprised we don't have in prod.

That was surprising to me too, and after checking, it appears we indeed don't have the license activated.

However, upon attempting to activate the license, it looks like the REST API endpoint for license activation is limited to Network Admins on a multisite network, as I am an Administrator on Learn WordPress.

```
{
    "code": "rest_forbidden",
    "message": "Sorry, you are not allowed to do that.",
    "data": {
        "status": 401
    }
}
```

@adamwoodnz who would be the best person to ask to get the license activated on the Learn WordPress site?

**Comment by adamwoodnz** [comment]
> who would be the best person to ask to get the license activated on the Learn WordPress site?

I'm a network admin so should be able to do it. Do we have a key? I'd expect the key that's been shared for local dev (Hugh shared one with me) to not be appropriate for prod... maybe need to ask the Sensei folks.

**Comment by jonathanbossenger** [comment]
@adamwoodnz I have that detail, I will send it to you directly.

**Pull request merged**
